import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {api,imageAllowed} from '../worker/api.js';
assert.equal(imageAllowed('http://example.com/image.png'),false);
assert.equal(imageAllowed('https://127.0.0.1/image.png'),false);
assert.equal(imageAllowed('https://example.local/image.png'),false);
assert.equal(imageAllowed('https://example.com/image.png'),true);
assert.equal(imageAllowed('data:image/svg+xml;base64,AAAA'),false);
let requests=[];globalThis.fetch=async(url,options)=>{requests.push(JSON.parse(options.body));const schema=requests.at(-1).text.format.name;const result=schema==='transcription'?{equation:'3x + 7 = 22',notes:'',readable:true}:schema==='solution'?{equation:'3x + 7 = 22',answer:'x = 5',detail:'One real solution.',steps:[{title:'Subtract 7',expression:'3x = 15',explanation:'Balance the equation.'}],check:['3(5) + 7 = 22']}: {passed:true,notes:'Substitution matches.'};return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(result)}]}]})};
const post=(path,body,origin)=>new Request('https://site.test'+path,{method:'POST',headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{})},body:JSON.stringify(body)});
const env={OPENAI_API_KEY:'test-placeholder'};
assert.equal((await api(post('/api/read',{image:'https://example.com/math.png'}),env)).status,200);
const solve=await (await api(post('/api/solve',{equation:'3x + 7 = 22'}),env)).json();assert.equal(solve.answer,'x = 5');assert.equal(solve.verification.passed,true);assert.equal(requests.length,3);
assert.equal((await api(post('/api/solve',{equation:''}),env)).status,400);
assert.equal((await api(post('/api/solve',{equation:'x=1'},'https://evil.test'),env)).status,403);
assert.equal((await api(post('/api/read',{image:'https://localhost/a.png'}),env)).status,400);
assert.equal((await api(post('/api/solve',{equation:'x=1'}),{})).status,503);
const source=await readFile('dist/server/index.js','utf8');const worker=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).default;assert.equal(typeof worker.fetch,'function');assert.equal((await worker.fetch(new Request('https://site.test/'),{})).status,200);assert.equal((await worker.fetch(new Request('https://site.test/style.css'),{})).headers.get('Content-Type'),'text/css; charset=utf-8');console.log('Worker, API validation, transcription, solution, separate check, and embedded assets passed.');
