const samples=[{equation:'2x + 8 = 20',answer:'x = 6',detail:'One real solution.',steps:[['Subtract 8 from both sides','2x = 12','Keep both sides balanced.'],['Divide both sides by 2','x = 6','Isolate the unknown.']],check:['Substitute x = 6 into the original equation.','2(6) + 8 = 20','12 + 8 = 20 ✓']},{equation:'x² − 5x + 6 = 0',answer:'x = 2 or x = 3',detail:'Two real solutions.',steps:[['Find two numbers that multiply to 6 and add to −5','−2 and −3','These numbers give us the factors.'],['Factor the quadratic','(x − 2)(x − 3) = 0','Expand the brackets to recover the original equation.'],['Set each factor equal to zero','x = 2 or x = 3','A product is zero when at least one factor is zero.']],check:['Substitute each candidate into the original equation.','x = 2: 4 − 10 + 6 = 0 ✓','x = 3: 9 − 15 + 6 = 0 ✓']},{equation:'(x + 1) / 3 = 4',answer:'x = 11',detail:'One real solution. The denominator is a nonzero constant.',steps:[['Multiply both sides by 3','x + 1 = 12','Clear the denominator.'],['Subtract 1 from both sides','x = 11','Isolate the unknown.']],check:['Substitute x = 11 into the original equation.','(11 + 1) / 3 = 4','12 / 3 = 4 ✓']}];
const $=id=>document.getElementById(id);let selected=1,current=null,objectUrl=null;const normal=s=>s.replaceAll('−','-').replaceAll('²','^2').replace(/\s/g,'').toLowerCase();
function clearResult(){current=null;$('result').hidden=true;$('empty').hidden=false;$('message').textContent='';}
function select(i){selected=i;clearResult();$('equation').value=samples[i].equation;$('sample-expression').textContent=samples[i].equation;$('sample-paper').hidden=false;$('upload-prompt').hidden=true;$('preview').hidden=true;document.querySelectorAll('[data-sample]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.sample)===i));if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null}$('file').value='';}
document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>select(Number(b.dataset.sample)));
function upload(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){$('message').textContent='Please choose a JPG, PNG or WebP image under 10 MB.';return}clearResult();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);$('preview').src=objectUrl;$('preview').hidden=false;$('sample-paper').hidden=true;$('upload-prompt').hidden=true;$('equation').value='';document.querySelectorAll('[data-sample]').forEach(b=>b.classList.remove('selected'));$('message').textContent='Photo ready. Demo mode cannot read uploaded images. Type one of the sample equations to explore its solution, or choose a sample below.';}
$('file').onchange=e=>upload(e.target.files[0]);$('drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('file').click()}};['dragenter','dragover'].forEach(name=>$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.add('over')}));['dragleave','drop'].forEach(name=>$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.remove('over');if(name==='drop')upload(e.dataTransfer.files[0])}));$('equation').oninput=clearResult;
function tab(name){$('steps').hidden=name!=='steps';$('check').hidden=name!=='check';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name))}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('solve').onclick=()=>{const s=samples.find(s=>normal(s.equation)===normal($('equation').value));if(!s){$('message').textContent=$('equation').value.trim()?'This equation is outside the three curated demos. Choose a sample to see a worked solution. Live solving needs an AI connection.':'Choose a sample or enter its equation first.';return}current=s;$('empty').hidden=true;$('result').hidden=false;$('message').textContent='';$('answer').textContent=s.answer;$('answer-detail').textContent=s.detail;$('steps').replaceChildren();s.steps.forEach((step,i)=>{const row=document.createElement('div');row.className='step';const num=document.createElement('span');num.textContent=i+1;const content=document.createElement('div');['h4','p','small'].forEach((tag,j)=>{const el=document.createElement(tag);el.textContent=step[j];content.append(el)});row.append(num,content);$('steps').append(row)});$('check').replaceChildren();s.check.forEach((text,i)=>{const p=document.createElement(i?'p':'div');p.textContent=text;$('check').append(p)});tab('steps')};
$('copy').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText([current.equation,current.answer,...current.steps.map(s=>s.join(': ')),...current.check,'Curated demo; no AI call made.'].join('\n'));$('copy').textContent='Copied ✓';setTimeout(()=>$('copy').textContent='Copy solution ↗',1800)}catch{$('message').textContent='Clipboard access is unavailable in this browser.'}};

let imageInput=null,sampleMode=true,busy=false;
function setBusy(value,message=''){busy=value;document.querySelectorAll('button,input').forEach(el=>el.disabled=value);$('message').textContent=message;}
async function callApi(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(200000)});const data=await response.json().catch(()=>({error:'Could not reach the AI service. Check your sign-in and connection.'}));if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
const demoSelect=select;select=i=>{if(busy)return;demoSelect(i);sampleMode=true;imageInput=null;$('read-image').hidden=true;$('image-url').value='';document.querySelector('.output-panel .pill').textContent='Sample solution';};
const previewUpload=upload;upload=file=>{if(busy)return;previewUpload(file);if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)return;imageInput=null;sampleMode=false;$('read-image').hidden=false;$('message').textContent='Photo ready. Select “Read equation from image” to transcribe it with AI.';const reader=new FileReader();reader.onload=()=>{imageInput=reader.result};reader.onerror=()=>{$('message').textContent='Could not read this file. Try another image.'};reader.readAsDataURL(file);};
$('load-url').onclick=()=>{if(busy)return;let url;try{url=new URL($('image-url').value.trim());if(url.protocol!=='https:'||url.username||url.password||!url.hostname.includes('.')||/^[\d.]+$/.test(url.hostname)||url.hostname.includes('localhost'))throw Error()}catch{$('message').textContent='Enter a public HTTPS link pointing directly to an image.';return}clearResult();sampleMode=false;imageInput=url.href;$('equation').value='';$('preview').referrerPolicy='no-referrer';$('preview').src=imageInput;$('preview').hidden=false;$('sample-paper').hidden=true;$('upload-prompt').hidden=true;$('read-image').hidden=false;document.querySelectorAll('[data-sample]').forEach(b=>b.classList.remove('selected'));$('message').textContent='URL ready. Read the image to transcribe its equation.';};
$('preview').onerror=()=>{$('message').textContent='Image preview unavailable. The link may require sign-in or may not point to an image. Try uploading the file instead.'};
$('read-image').onclick=async()=>{if(busy)return;if(!imageInput){$('message').textContent='The image is still loading. Please try again.';return}clearResult();setBusy(true,'Reading your equation…');try{const data=await callApi('/api/read',{image:imageInput});$('equation').value=data.readable?data.equation:'';sampleMode=false;setBusy(false,data.readable?'Equation read. Review it before solving. '+data.notes:data.notes||'No clear equation found. Try a closer, sharper photo.');document.querySelector('.output-panel .pill').textContent='Live AI';}catch(e){setBusy(false,e.name==='TimeoutError'?'The image request timed out. Please try again.':e.message)}};
$('equation').oninput=()=>{clearResult();sampleMode=false;document.querySelectorAll('[data-sample]').forEach(b=>b.classList.remove('selected'));};
function renderLive(s){current={...s,steps:s.steps.map(step=>[step.title,step.expression,step.explanation])};$('empty').hidden=true;$('result').hidden=false;$('answer').textContent=s.answer;$('answer-detail').textContent=s.detail;$('steps').replaceChildren();current.steps.forEach((step,i)=>{const row=document.createElement('div');row.className='step';const num=document.createElement('span');num.textContent=i+1;const content=document.createElement('div');['h4','p','small'].forEach((tag,j)=>{const el=document.createElement(tag);el.textContent=step[j];content.append(el)});row.append(num,content);$('steps').append(row)});$('check').replaceChildren();[...s.check,'Separate model review: '+s.verification.notes].forEach((text,i)=>{const p=document.createElement(i?'p':'div');p.textContent=text;$('check').append(p)});document.querySelector('.output-panel .pill').textContent=s.verification.passed?'Model check passed':'Review needed';document.querySelector('.result-bottom>span').textContent='✧ AI-generated · verify important results';tab('steps');}
const demoSolve=$('solve').onclick;$('solve').onclick=async()=>{if(busy)return;if(sampleMode){demoSolve();document.querySelector('.result-bottom>span').textContent='✧ Curated demo · no AI call made';return}const equation=$('equation').value.trim();if(!equation){$('message').textContent='Read your image or enter an equation first.';return}if(equation.length>1500){$('message').textContent='Use an equation under 1,500 characters.';return}clearResult();setBusy(true,'Solving and checking your equation…');try{const s=await callApi('/api/solve',{equation});renderLive(s);setBusy(false,s.verification.passed?'':s.verification.notes)}catch(e){setBusy(false,e.name==='TimeoutError'?'The solution request timed out. Please try again.':e.message)}};
$('copy').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText([current.equation,current.answer,...current.steps.map(s=>s.join(': ')),...current.check,sampleMode?'Curated demo; no AI call made.':'AI-generated; verify important results.'].join('\n'));$('copy').textContent='Copied ✓';setTimeout(()=>$('copy').textContent='Copy solution ↗',1800)}catch{$('message').textContent='Clipboard access is unavailable in this browser.'}};
